# PostgreSQL configuration for meppi-rails
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000

development:
  <<: *default
  database: meppi_rails_development
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  username: <%= ENV.fetch("POSTGRES_USER", "meppi_rails") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>

test:
  <<: *default
  database: meppi_rails_test
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  username: <%= ENV.fetch("POSTGRES_USER", "meppi_rails") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>

production:
  <<: *default
  database: meppi_rails_production
  url: <%= ENV.fetch("DATABASE_URL") %>
